api:
  port: &port 9045
#  url: http://localhost:*port/inspur_track

det:
  source: E:\work\AI_Project\ComputerVision\target_track\deep_tracking\examples\cat.mp4
  model_path: D:/Inspur/base_model/yolo8/yolov8s.pt
  device: None
  img_size: 640
  threshold: 0.3
  conf_thres: 0.25
  iou_thres: 0.45
  stride: 1
  target: ['person', 'car', 'truck', 'cat']
  half: False


track:
  method: deep_sort
  max_history_id: 50    # 丢失超过多少帧就删除