api:
  port: 9045
  host: 192.168.12.84

det:
#  source: E:\work\AI_Project\ComputerVision\target_track\deep_tracking\examples\cat.mp4
  source: E:\work\AI_Project\ComputerVision\target_track\yolo_tracking\examples\test.mp4
#  source: 0
  model_path: D:/Inspur/base_model/yolo8/yolov8n.pt
  device: cpu
  img_size: 640
  threshold: 0.3
  conf_thres: 0.25
  iou_thres: 0.45
  stride: 1
  target: ['person', 'car', 'truck', 'cat']
  half: False


track:
  api: False    # use api
  method: deep_sort   # use track method
  max_history_id: 50  # allow lost max frames
  save: True
  save_path: ./save_result
  track_target: ['cat', 'car', 'person']
  show: True